### ISSUE TITLE
Virus/Trojan alert 4/14/2023

### ISSUE THREAD

**Issue by Rhomboides** [hfiref0x/AuthHashCalc#4]
When downloading the zip of the source and binaries, MSFT Defender detects a threat (critical Trojan:Win32/Crysant) in the Source/tests/bin/BadNTHeaders.exe file.  McAfee Endpoint Security detects a threat:  AuthHashCalc-master.zip\corkami_pe_bin.7z\96emptysections.exe. The Trojan named Artemis!A910C7442D86 was detected.

**Comment by hfiref0x** [comment]
Universal solution for this schizophrenic scamware built-in Windows.

1) Boot into Windows Safe Mode.
2) Go to Windows\system32\drivers, take ownership over file WDFilter.sys (it is owned by TrustedInstaller by default). Also the "wd" subdirectory here, take ownership too.
3) remove this file, "wd" directory and all the files inside.
4) Open regedit, navigate to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services
5) Find a WDFilter reg entry, take ownership - remove it. Do the same for all the WD entries here, especially to it service.
6) Now go to %Program Files% find all the "Windows Defender bla-bla-blah" directories, take ownership over them and all it contents, remove them completely. Some files maybe in use, but this is doesn't really matter.
7) Double check that you removed everything from WD in "system32\drivers", "drivers\wd", registry and program files.
8) Reboot your PC. Congratulations you are liberated from insanely idiotic AV.

What about McAfee - here is all what you need to know about it.
[How To Uninstall McAfee Antivirus](https://www.youtube.com/watch?v=LateGH26PT4)
