### ISSUE TITLE
The calculated value seems to be different from the value inside the signdata.contentinfo

### ISSUE THREAD

**Issue by Fallen-Tiger** [hfiref0x/AuthHashCalc#5]
filemd5: 6ca0e567d6c2d6508b350d727b30e607
calculated result: dd371112f957f650a22303b403abd6a9426a1b584785f214097f9702600a6801
contentinfo authenticode hash: d46cea20a0a347850242069e3d6b4c646c16a4bb50ca98d158188c6208b3d5bc
but windows pass the check

**Comment by hfiref0x** [comment]
So what is your question here?

**Comment by Fallen-Tiger** [comment]
So your calculation and Windows should have one is wrong

**Comment by hfiref0x** [comment]
Your file is https://www.virustotal.com/gui/file/da6235c9e5ff9d5d17120130adfb90db3e83a1f45bd76e7d5ac562620c3419cf

I don't have it and won't bother looking on it if you don't provide actual info what you are talking about.

"signdata.contentinfo"
there are tons of structures with similar fields, I should guess what exactly this by it field name only?
Authentihash for this file is dd371112f957f650a22303b403abd6a9426a1b584785f214097f9702600a6801
Whatever you are looking at it is wrong.
