### ISSUE TITLE
Inaccurate Authenticode hash calculations

### ISSUE THREAD

**Issue by brian763** [hfiref0x/AuthHashCalc#7]
[5CC4A75354719C10460C6881A822DA38.zip](https://github.com/user-attachments/files/16721385/5CC4A75354719C10460C6881A822DA38.zip)

**Comment by brian763** [comment]
![image](https://github.com/user-attachments/assets/b6574b1c-b728-4f9e-a775-03c284c4665b)

```
PS C:\Users\Root\Desktop> cd C:\sss
PS C:\sss> Get-CiFileHashes -FilePath "C:\sss\5CC4A75354719C10460C6881A822DA38"

SHA1Page SHA256Page SHa1Authenticode                         SHA256Authenticode
-------- ---------- ----------------                         ------------------
                    50E201C5815BC2A4D01475C34431F09A377D1558 78794638006D93DC62BA1B6D0E8DCF08E7D7E264B5B0562EED890B30C0EA87D3

PS C:\sss> .\ahc64.exe 5CC4A75354719C10460C6881A822DA38
PS C:\sss>
AuthHashCalc v1.0.4.2402 built at Thu Feb 22 08:44:22 2024

File: 5CC4A75354719C10460C6881A822DA38

Authenticode hashes:
MD5:    A1E9B8C88EEF2D8B326AE234F0D4FBA5
SHA1:   EE3513A4F8DA799912D1CBAD5A94B17D41F1BA66
SHA256: D13551E2DA882E6135497FA639DFBE9160AB62BD5AD529D8582A2E7B20134C6F
SHA384: 94BD4C4342EA2AA4172E74D6212E5AEF959D13A0076A030332CE856577FC8BADA67D8319EC5EAEC1309BE6EF43496A60
SHA512: F7FFDB956C91E1C52EFBC430C4E7CBA1221B2EC5F71C425CE4D862AF18D90EEAD04429B40B9869333CD3ECAC631A8C92F183E2175C6AD033E0D1AE9725FEF0AF

First page hash:
SHA1:   7509BBDA365AA1459FDE5B5722E8FFC5CEB75D16
SHA256: 7B8CF6AA9EB1D4A806BEF5C8C42070440E1885AABC11D1EBFE13B8B817F9C031

Completed.
```

**Comment by hfiref0x** [comment]
This file is a corrupted memory dump.

**Comment by brian763** [comment]
> This file is a corrupted memory dump.

However, I have fortuitously discovered that your AuthHashCalc computes a SHA256 value that coincides with one in the catalog directory. May I kindly inquire if there are any plans to adjust the logic to avert such occurrences? For instance, by filtering out those files that may be corrupted. Thank you!
![image](https://github.com/user-attachments/assets/a33baa9e-fda0-4e2d-bc1b-823c6e6992eb)
[CodeIntegrity.zip](https://github.com/user-attachments/files/16731874/CodeIntegrity.zip)

**Comment by hfiref0x** [comment]
The file you submitted first is a raw memory dump including some part of Kingsoft AV binary data. The actual PE file in this raw dump has ~20KB in size and it is apiset stub dll with authenticode hash d13551e2da882e6135497fa639dfbe9160ab62bd5ad529d8582a2e7b20134c6f. I don't know what should I fix there. Probably it's Get-CiFileHashes should fix it behaviour and not calculate all kind of beyond what is actually PE file.
